spring:
  datasource:
    url: jdbc:mysql://localhost:3306/escola?useSSL=false
    username: cell
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    
    properties:
      hibernate.format_sql: true